 var hotels = [
    { id: "1",
    name: "COX'S BAZAR",
    hotelName:"Sea Gull Hotel",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(20)",
    roomImage:"https://i.ibb.co/SKrMwGV/hotel1.png",
    price:"$34/night  $167 total"},

    { id: "1",
    name: "COX'S BAZAR",
    hotelName:"Sea Paradise",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.8(10)",
    roomImage:"https://i.ibb.co/ssTtKDM/hotel2.png",
    price:"$34/night  $167 total"},

    { id: "1",
    name: "COX'S BAZAR",
    hotelName:"Ocean Dream ",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(25)",
    roomImage:"https://i.ibb.co/vsWTT3p/hotel3.png",
    price:"$34/night  $167 total"},

    { id: "2",
    name: "SAJEK",
    hotelName:"Cox,s Bazaar",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(20)",
    roomImage:"https://i.ibb.co/SKrMwGV/hotel1.png",
    price:"$34/night  $167 total"},

    { id: "2",
    name: "SAJEK",
        hotelName:"Apartment in Lost Panorama",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.8(10)",
    roomImage:"https://i.ibb.co/ssTtKDM/hotel2.png",
    price:"$34/night  $167 total"},

    { id: "2",
    name: "SAJEK",
    hotelName:"AR Lounge & Pool (r&r + b&B) ",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(25)",
    roomImage:"https://i.ibb.co/vsWTT3p/hotel3.png",
    price:"$34/night  $167 total"},

    { id: "3",
    name: "SREEMONGOL",
    hotelName:"Cox,s Bazaar",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(20)",
    roomImage:"https://i.ibb.co/SKrMwGV/hotel1.png",
    price:"$34/night  $167 total"},

    { id: "3",
    name: "SREEMONGOL",
        hotelName:"Apartment in Lost Panorama",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.8(10)",
    roomImage:"https://i.ibb.co/ssTtKDM/hotel2.png",
    price:"$34/night  $167 total"},

    { id: "3",
    name: "SREEMONGOL",
    hotelName:"AR Lounge & Pool (r&r + b&B) ",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(25)",
    roomImage:"https://i.ibb.co/vsWTT3p/hotel3.png",
    price:"$34/night  $167 total"},
    
    { id: "4",
    name: "SUNDORBON",    
    hotelName:"Cox,s Bazaar",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(20)",
    roomImage:"https://i.ibb.co/SKrMwGV/hotel1.png",
    price:"$34/night  $167 total"},

    { id: "4",
    name: "SUNDORBON",    
        hotelName:"Apartment in Lost Panorama",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.8(10)",
    roomImage:"https://i.ibb.co/ssTtKDM/hotel2.png",
    price:"$34/night  $167 total"},

    { id: "4",
    name: "SUNDORBON",
    hotelName:"AR Lounge & Pool (r&r + b&B) ",
    details:"4 guests 2 bedrooms 2 beds 2 baths wifi Air conditioning kitchen Cancellation fexibility availiable",
    rank:"4.9(25)",
    roomImage:"https://i.ibb.co/vsWTT3p/hotel3.png",
    price:"$34/night  $167 total"}
        ]

export default hotels;